### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by AdyStudios** [kristofhracza/tim_apple#10]
Hello!
I can't seem to be able to open up the project in visual studio 2022. I get this error: 
![image](https://github.com/kristofhracza/tim_apple/assets/74962285/2304d69f-b49f-4ce5-a986-68262c5eb71c)

**Comment by kristofhracza** [comment]
1. Open `Visual Studio Installer`
2. Click on `Modify` next to `Visual Studio Community 2022`
3. Download the `Desktop Development with C++` package 

[Similar issue](https://stackoverflow.com/questions/45613218/unsupported-this-version-of-visual-studio-is-unable-to-open-the-following-projec)
There might be more help in the above mentioned post
