### ISSUE TITLE
literally cant decipher instructions not a coder

### ISSUE THREAD

**Issue by Cashelious** [kristofhracza/tim_apple#11]
![image](https://github.com/kristofhracza/tim_apple/assets/149124866/606db0f4-a6b0-4ccd-a994-c467974e3d45)

When I build the sln file there are multiple errors that pop up can somebody give me simple instructions on what to do to get the exe file.

**Comment by kristofhracza** [comment]
That is plain english, you don't have to be able to code lol

It says that it cannot open the files.

Maybe you donwnloaded the files with admin privileges, meaning you would have to open the editor with admin privileges as well.

If not, just make sure that files are all there.

[This](https://learn.microsoft.com/en-us/answers/questions/532821/error-cannot-open-source-file-in-c) might help you
