### ISSUE TITLE
not working after new update

### ISSUE THREAD

**Issue by kadem22** [kristofhracza/tim_apple#14]
The cheat does not work after the new update, esp still works but the aimbot and trigger bot do not

**Comment by kristofhracza** [comment]
Update offsets!

[https://github.com/kristofhracza/tim_apple?tab=readme-ov-file#offsets](https://github.com/kristofhracza/tim_apple?tab=readme-ov-file#offsets)

**Comment by kadem22** [comment]
hmm, yesterday i updated them however it did not work still, i think i got them from the wrong place, but when i used the link in the readme it worked, thanks!

**Comment by kadem22** [comment]
hello now the esp is very laggy, its almost unplayable and the aimbot locks onto the box but the box is not where the player is so its very hard to play with
