### ISSUE TITLE
Skeletons are lagging + only draws to half an ultrawide screen

### ISSUE THREAD

**Issue by BigBoss49** [kristofhracza/tim_apple#17]
probably a small fix but idk c++ that well. everything else works great tho

**Comment by kristofhracza** [comment]
The lagging is a server side issue, there's nothing I can do about that.

As for the ultrawide monitor I am not sure what the issue could be, but please note that the cheat will only work in 16:9 ratio.

**Comment by BigBoss49** [comment]
it actually works fine its just the esp thats lagging really. i found that if you are on the pause menu that it works perfectly. A vague theory i have is its a game optimization but i dont know enough about source 2 to really say if thats the reason.

**Comment by BigBoss49** [comment]
i havent had an issue with the aimbot 9/10 of the time

**Comment by kristofhracza** [comment]
Weird. No one had any issue with the normal ESP before.
However, the item ESP will lagg, because it isn't optimised yet.
