### ISSUE TITLE
Running the exe does nothing.

### ISSUE THREAD

**Issue by M4zeRain** [kristofhracza/tim_apple#18]
Cloned, built release  on x64 and running the .exe with the game already open nothing happens. I press insert and no menu, no anything.

**Comment by kristofhracza** [comment]
Read the README to make sure it works.

Note that it won't work unless you're apsect ratio is 16:9

**Comment by M4zeRain** [comment]
I read the README and did as the instructions said, Built release on x64 and ran the tim_apple.exe with the game running. (this was before the "A CALL TO ARMS" update that happened today, so that wasn't the issue either.) Running the exe did nothing no matter if i ran it as admin or not. My aspect ratio is 16:9, game was running in windowed borderless or as it's called in cs2: "FULLSCREEN WINDOWED", tho that isn't in the README so idk. Disabling my antivirus didn't help either. The debug x64 doesn't compile without errors anyway so i couldn't have built the debug and thought i built the release. And with all of that pressing insert did nothing, so I don't know where to proceed from here.

**Comment by kristofhracza** [comment]
Are the offset files in the same folder as the `tim_apple.exe` is?

**Comment by M4zeRain** [comment]
Yeah having the offsets fixed it. I just didn't know you needed them just to launch the cheat. I wanted to make sure i compiled everything correctly before updating offsets or anything like that. Sorry, i  just didn't know you had to have the offsets for the cheat to run.
