### ISSUE TITLE
Recoilcontrol doesn't work

### ISSUE THREAD

**Issue by JeepEda** [kristofhracza/tim_apple#19]
Since cs2 updated today, I also updated offset, other things are work, but the recoilcontroldoes not work

**Comment by kristofhracza** [comment]
How did you update the offsets? Remote or manual?

If remote, try it manually.

**Comment by JeepEda** [comment]
i updated offsets from cs2 dumper, but could it be caused by the wrong value from these offset?

**Comment by kristofhracza** [comment]
It could be, though I haven't downloaded the new update yet to try it out.

**Comment by JeepEda** [comment]
Maybe the offset is wrong. Thank you for your code. Thank you for your answer.

**Comment by JeepEda** [comment]
May I ask which offset recoilcontrol use?

**Comment by JeepEda** [comment]
Recoilcontrol runs a few times at first, but after that, it doesn't work at all
