### ISSUE TITLE
What new things to expect

### ISSUE THREAD

**Issue by 1arsi1** [kristofhracza/tim_apple#2]
What are your future plans for development?

**Comment by kristofhracza** [comment]
I think that the cheat is pretty much done, but I'll add the following features sometime in the future:

- Item ESP
- Aimbot `mouse_event`

**Comment by 1arsi1** [comment]
Oh, nice, maybe u have discord community for this hack?

**Comment by kristofhracza** [comment]
No I don't have one

**Comment by 1arsi1** [comment]
Maybe just create him? hah)

**Comment by kristofhracza** [comment]
Not rly
Anyhow, I'll close this issue.
