### ISSUE TITLE
Aimbot buggy

### ISSUE THREAD

**Issue by boyo3473** [kristofhracza/tim_apple#21]
Hey there i love this project it is really good but the aimbot is really buggy it lags back somtimes somone else i know has tested it to and has the same bug i have been making my own external with your base i added team check to and fixed some visual bugs 
is there any way you can update the aimbot to be better?
![image](https://github.com/kristofhracza/tim_apple/assets/141408370/3e12f186-4e8d-4e6e-bb67-6e338977de9c)

**Comment by kristofhracza** [comment]
I just moved by base OS to linux, I'll install windows in the coming days and will come back to you.

**Comment by boyo3473** [comment]
> I just moved by base OS to linux, I'll install windows in the coming days and will come back to you.

alr thank you

**Comment by boyo3473** [comment]
> I just moved by base OS to linux, I'll install windows in the coming days and will come back to you.
this is a short clip of what its doing if you need to know

**Comment by kristofhracza** [comment]
Can you link a video of it lagging? 
Just because when tested, it works for well for me

**Comment by boyo3473** [comment]
> Can you link a video of it lagging? Just because when tested, it works for well for me

can you add me on discord so i can send you a clip it wont let me here username: boyo_39080

**Comment by kristofhracza** [comment]
Upload the video here: https://streamable.com/

**Comment by boyo3473** [comment]
> Can you link a video of it lagging? Just because when tested, it works for well for me

i seem to be getting a new bug after the new update i tryed updating the offsets but now when i try load it the gui does not load

**Comment by kristofhracza** [comment]
This was the last update: https://store.steampowered.com/news/app/730?emclan=103582791432902485&emgid=4185606994270578440

I fixed the cheat yesterday and it has been working for everyone.

**Comment by boyo3473** [comment]
> This was the last update: https://store.steampowered.com/news/app/730?emclan=103582791432902485&emgid=4185606994270578440
> 
> I fixed the cheat yesterday and it has been working for everyone.

i download your last update and that does not load to i redownload the offsets put gui does not render

**Comment by kristofhracza** [comment]
did you download the [buttons file](https://github.com/a2x/cs2-dumper/blob/main/output/buttons.json)

**Comment by boyo3473** [comment]
> did you download the [buttons file](https://github.com/a2x/cs2-dumper/blob/main/output/buttons.json)

oh wait i will try that

**Comment by boyo3473** [comment]
> did you download the [buttons file](https://github.com/a2x/cs2-dumper/blob/main/output/buttons.json) ?

yours now works what did you update in your source? (aimbot bug btw https://streamable.com/tvsy0u)

**Comment by kristofhracza** [comment]
That's not exacty a bug.
The aimbot doesn't compensate for the speed of moving...

I might add a feature that does that, however I will now close this issue as completed.
