### ISSUE TITLE
Offsets crash tim_apple

### ISSUE THREAD

**Issue by Netshh** [kristofhracza/tim_apple#23]
a2x deleted the offset repo how do i get new one?

**Comment by Netshh** [comment]
now i can't open tim_apple.exe i already turn off antivirus and pressed insert but the window won't show now.

**Comment by lfajak2** [comment]
I have same problem

**Comment by kristofhracza** [comment]
Added new one, check the links

**Comment by kristofhracza** [comment]
I've just pushed a new update.
Whilst there's still an issue with the dumper, I've adjusted the code to the new layout, so once the dumper works
the cheat will work too.
