### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Kumarbaging** [kristofhracza/tim_apple#24]
doesnt work

**Comment by kristofhracza** [comment]
That's not much I can work with

**Comment by Ruabc123** [comment]
well if i had to guess, it doesnt work, there isnt really much else to add ive added the offsets files and it opens then closes

**Comment by kristofhracza** [comment]
The offset dumper of a2x doesn't work. Once the fix for that is out, it will work.
https://github.com/a2x/cs2-dumper/issues/106

**Comment by kristofhracza** [comment]
I've just pushed a new update.
Whilst there's still an issue with the dumper, I've adjusted the code to the new layout, so once the dumper works
the cheat will work too.
