### ISSUE TITLE
Offsets crash tim_apple

### ISSUE THREAD

**Issue by TheKetur55** [kristofhracza/tim_apple#27]
Doesn't work anymore since the last csgo update (impossible to launch)

**Comment by TheKetur55** [comment]
J'ai reconstruit avec la dernière version du logiciel + offsets / client.dll.json

**Comment by serizava01** [comment]
Press open and nothing happens like the program can't find the game.

**Comment by kristofhracza** [comment]
The offset dumper of a2x doesn't work. Once the fix for that is out, it will work.
https://github.com/a2x/cs2-dumper/issues/106

**Comment by kristofhracza** [comment]
I've just pushed a new update.
Whilst there's still an issue with the dumper, I've adjusted the code to the new layout, so once the dumper works
the cheat will work too.

**Comment by lfajak2** [comment]
Offsets have been updated, but the tim_apple cheat still doesn't work.

**Comment by Ruabc123** [comment]
looks like there was some sort of fix or experimental fix for cs2 dumper but idk if it fixed it fully, still doesnt work not sure if its because of cheat or dumper but just thought id let you know

**Comment by kristofhracza** [comment]
https://github.com/a2x/cs2-dumper/issues/106

It's not fixed yet

**Comment by kristofhracza** [comment]
I neglected some features in the cheat yesterday, which I updated just now.

In theory it should work, though I can only test it tomorrow.

**Comment by kristofhracza** [comment]
Refer to this issue: https://github.com/kristofhracza/tim_apple/issues/28

**Comment by TheKetur55** [comment]
okey thanks

**Comment by kristofhracza** [comment]
This is the final fix: https://github.com/kristofhracza/tim_apple/commit/2fc4dc73b558786f2f049e7d57e394c2b6da4dc1

As of now the cheat works, as I personally tested it
