### ISSUE TITLE
Errors upon compilation

### ISSUE THREAD

**Issue by discordplebs** [kristofhracza/tim_apple#28]
i get these 4 errors when compiling: 

Error	C2039	'buttonsFile': is not a member of 'offsets' - tim_apple-master\features\misc.cpp  line6
Error	C2065	'buttonsFile': undeclared identifier - tim_apple-master\features\misc.cpp  line6	
Error	C2039	'buttonsFile': is not a member of 'offsets' - tim_apple-master\features\misc.cpp  line9	
Error	C2065	'buttonsFile': undeclared identifier - tim_apple-master\features\misc.cpp  line9	

how to fix this?

**Comment by craxking** [comment]
![Screenshot_2](https://github.com/kristofhracza/tim_apple/assets/58630179/fbee39e3-a2ea-4d7b-9c09-eb54b94a378d)
**same here...project is throwing me bunch of errors**

**Comment by kristofhracza** [comment]
I pushed a new update regrading your issue.
Please keep in mind that I don't yet have an env. to check for the all the bugs.

I'll start tesitng this weekend, as of right now I'm just eyeballing it.

**Comment by kristofhracza** [comment]
If you still have a new issue, please just add it here.

I’ll get onto it tomorrow.

**Comment by craxking** [comment]
> If you still have an issue, please just add it here.
> 
> I’ll get onto it tomorrow.

yeah its still giving some errors
but its ok brother take your time to fix it properly :)
![Screenshot_2](https://github.com/kristofhracza/tim_apple/assets/58630179/c265422f-703f-4eb7-905b-ca754dcf34df)

**Comment by discordplebs** [comment]
yes same, we shall wait :D

**Comment by kristofhracza** [comment]
Thank you guys,

I don’t have windows installed atm, but will install it tomorrow.
So, expect the update tomorrow evening. Given that I can fix it.

Cheers

**Comment by FilmGOTY** [comment]
A stupid solution, even until it is fixed
![image](https://github.com/kristofhracza/tim_apple/assets/77454891/e4560f14-63ae-4ffe-a3ed-03b99667e1cc)

**Comment by mai0385** [comment]
> A stupid solution, even until it is fixed ![image](https://private-user-images.githubusercontent.com/77454891/320172000-e4560f14-63ae-4ffe-a3ed-03b99667e1cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzU0OTAsIm5iZiI6MTcxMjM3NTE5MCwicGF0aCI6Ii83NzQ1NDg5MS8zMjAxNzIwMDAtZTQ1NjBmMTQtNjNhZS00ZmZlLWEzZWQtMDNiOTk2NjdlMWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAzNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ODU0MzYzNzg2YjlmNDk0YTZlZDQ3YjJmYzUwOTEwMjZiYzg3MThlMDlhNDY5NjBkMzM1OWUxMGRiOGRmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZAMoJcY6wZmHdmsWOFDBW-SBsukPPuPI-1WyNthU6YQ)

that fix ?

**Comment by hgttt** [comment]
> A stupid solution, even until it is fixed ![image](https://private-user-images.githubusercontent.com/77454891/320172000-e4560f14-63ae-4ffe-a3ed-03b99667e1cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDEwNDAsIm5iZiI6MTcxMjQwMDc0MCwicGF0aCI6Ii83NzQ1NDg5MS8zMjAxNzIwMDAtZTQ1NjBmMTQtNjNhZS00ZmZlLWEzZWQtMDNiOTk2NjdlMWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEwNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMmJiMjhkYTE4MGMwZjVhMzEzNmNiN2Q4Yzc0NTRlMDNkYjZkNzJiNzcxYzUzMDlhMzE2NTlmMjIxOWRjMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.enIKQnhAXY-u7j2iwA988aGKpjsyRfo8f31gxhrdPFI)

i have never made a github account but i havent ever seen a fix so simple and so smart at the same time. thank you so much

**Comment by hgttt** [comment]
the cheat doesnt open though now. when you run the cheat it just crashes

**Comment by FilmGOTY** [comment]
> the cheat doesnt open though now. when you run the cheat it just crashes

try this
![image](https://github.com/kristofhracza/tim_apple/assets/77454891/36ee9256-1e60-4998-b194-3b220f1b80dc)

**Comment by kristofhracza** [comment]
This is the final fix: https://github.com/kristofhracza/tim_apple/commit/2fc4dc73b558786f2f049e7d57e394c2b6da4dc1

As of now the cheat works, as I personally tested it

**Comment by craxking** [comment]
> This is the final fix: [2fc4dc7](https://github.com/kristofhracza/tim_apple/commit/2fc4dc73b558786f2f049e7d57e394c2b6da4dc1)
> 
> As of now the cheat works, as I personally tested it

everything is fine but when i double click the exe...cheat doesnt start...nothing happens!!
am i doing something wrong?

**Comment by kristofhracza** [comment]
That cannot be since I just tested it.

Make sure you have the latest version and downloaded all the offset files.

**Comment by craxking** [comment]
> That cannot be since I just tested it.
> 
> Make sure you have the latest version and downloaded all the offset files.

my bad..**offsets were not downloaded**... ### its working fine now..thanks brother !!!
