### ISSUE TITLE
"Timapple.exe" does not inject cheat.

### ISSUE THREAD

**Issue by uagvaq** [kristofhracza/tim_apple#30]
Hello, can I please ask for your assistance on this? So, I built the solution in Visual Studio, I go to the .exe file with my game open, I run the .exe file, and nothing happens. Can you please tell me if I'm doing something wrong? Thanks.

**Comment by uagvaq** [comment]
Note: I am also clicking the INSERT key for what would open the cheat and nothing happens there either.

**Comment by kristofhracza** [comment]
Did you follow this guide? https://github.com/kristofhracza/tim_apple?tab=readme-ov-file#offsets

**Comment by uagvaq** [comment]
Yeah, I did that too. I did the "manual download" thing and it still doesn't work. Apologies for not mentioning that earlier.

**Comment by uagvaq** [comment]
Is there anything that I should be doing when I inject the cheat? It's just run the .exe file with the game open right?

**Comment by kristofhracza** [comment]
Whend did you download the repo?
If it's earlier than yesterday then download it again

**Comment by uagvaq** [comment]
Nope, I have the repo from yesterday downloaded and built. Sorry for the late response, btw.

**Comment by kristofhracza** [comment]
Can you send me the logs from the build process?

**Comment by uagvaq** [comment]
Hey mate, I'm terribly sorry for the super late response, but where do I get the build logs?

**Comment by kristofhracza** [comment]
When you build the project in Visual Studio, there's a console which shows the errors / warnings.
Just take a screenshot of that area, please make sure that all info can be seen.

**Comment by kristofhracza** [comment]
Closing the issue due to lack of repsonse...

**Comment by kristofhracza** [comment]
Closing the issue due to lack of response..
