### ISSUE TITLE
overlay size

### ISSUE THREAD

**Issue by boyo3473** [kristofhracza/tim_apple#33]
is there a way to make the overlay size bigger to fit all the screen to the right of the screen the esp does not draw

**Comment by kristofhracza** [comment]
No as that's not a feature.

**Comment by boyo3473** [comment]
> No as that's not a feature.

why is it like that is what im asking and how can i resize the overlay

**Comment by kristofhracza** [comment]
As I mentioned it's not a feature.
If you want to edit the code yourself, there's 100% a solution online.
