### ISSUE TITLE
This is not an issue its just somthing i want to give to you (team check)

### ISSUE THREAD

**Issue by boyo3473** [kristofhracza/tim_apple#34]
idk if you want it but here i added team check ```		if (aimConf.teamcheck) {
			if (C_CSPlayerPawn.pawnHealth <= 0 || C_CSPlayerPawn.pawnHealth > 100 || strcmp(CCSPlayerController.pawnName.c_str(), "DemoRecorder") == 0 || localPlayer.getTeam() == CCSPlayerController.getPawnTeam()) {
				continue; 
			}
		}
		else {
			if (C_CSPlayerPawn.pawnHealth <= 0 || C_CSPlayerPawn.playerPawn == localPlayer.getPlayerPawn()) {
				continue; 
			}
		}
```

**Comment by kristofhracza** [comment]
I will take it into consideration, thanks!

**Comment by boyo3473** [comment]
> I will take it into consideration, thanks!

np

**Comment by Mespeet** [comment]
Why not just make a pull request?  ╯︿╰
