### ISSUE TITLE
cs2 has updated again so i updated the offsets but its doing the same thing as last time where it does not render the gui or anything 

### ISSUE THREAD

**Issue by boyo3473** [kristofhracza/tim_apple#35]
any fix or somthing i can do manual?

**Comment by boyo3473** [comment]
i think its the entity list offset when i update it the overlay crash

**Comment by boyo3473** [comment]
> Everything should work fine, make sure you have the latest offsets downloaded

i have i made a c++ program to auto update the files and if i use the old ones the gui loads fine but when i update them it crashs

**Comment by kristofhracza** [comment]
Can you explain it better?

**Comment by kristofhracza** [comment]
Closing due to lack of communication...
