### ISSUE TITLE
not getting a .exe file

### ISSUE THREAD

**Issue by ajakissnsndj** [kristofhracza/tim_apple#44]
whenever i build it with just the Tim apple sln file i dont get an exe, and whenever i just clone the repository, i still dont get one, can u help??

**Comment by louisergi1** [comment]
i think this got something with windows security thing? cuz mine was also got quarantined

**Comment by kristofhracza** [comment]
You won't get an executable just by cloning the repo. You have to build the project.

As for not getting the exe, I have no idea. Maybe provide some extra info?

**Comment by Tempritscher** [comment]
use visual studio, import the project, change project from debug to release and press build to compile to project to an exe.
Keep in mind that you need the latest offset files in order to run the project.

**Comment by ajakissnsndj** [comment]
yes, i'm doing exactly that, but it says failed, and i'm not getting an exe

**Comment by kristofhracza** [comment]
Does it exactly say: “failed”?
If not, give me the error message…
