### ISSUE TITLE
Problem esp skeleton 

### ISSUE THREAD

**Issue by Lukz4i20** [kristofhracza/tim_apple#45]
Firstly, thank you for your contribution, I've been using it for months and it's intact, after the last update, ESP SKELETON stopped working, can you help me with what it could be?

https://imgur.com/ONtXuTO

**Comment by kristofhracza** [comment]
Thank you mate, it's fun making it!

It's related to this issue: https://github.com/a2x/cs2-dumper/issues/155
Once it's fixed by a2x, skeleteon ESP should work.
