### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by 1arsi1** [kristofhracza/tim_apple#5]
![image](https://github.com/kristofhracza/tim_apple/assets/61199844/374e3c77-8309-4949-be29-f73fcced9a50)

**Comment by 1arsi1** [comment]
![image](https://github.com/kristofhracza/tim_apple/assets/61199844/a048b742-51f6-408a-bf91-8acd3f1c9095)

**Comment by 1arsi1** [comment]
![image](https://github.com/kristofhracza/tim_apple/assets/61199844/93151d4e-2ce6-4616-a28a-8705e8d9978a)

**Comment by 1arsi1** [comment]
![image](https://github.com/kristofhracza/tim_apple/assets/61199844/a7923070-313e-457d-adab-8ba7ebc906ab)
wtf hahaha

**Comment by kristofhracza** [comment]
The icon mapping issue has been [fixed](https://github.com/kristofhracza/tim_apple/commit/a19f44d14bb3b2845880f2727272541b745255dd) .

The `SSG` and the `XM1014` don't show. It is not a matter of fonts.
I'll fix it later.

I don't know how you were able to map `deagle` icon onto an `ak` [HERE](https://github.com/kristofhracza/tim_apple/issues/5#issuecomment-1872929813), you might have an old version of the code. Please make sure you update it, as you might have a version where the `ak` has a different value. That was a bug that was fixed! 

If the issue still persists, submit another one.
