### ISSUE TITLE
aimbot detected?

### ISSUE THREAD

**Issue by kadem22** [kristofhracza/tim_apple#8]
Is the aimbot read and write or read only? and is it easy to get u banned? sorry if its a dumb question but im new

**Comment by kristofhracza** [comment]
As for now, the cheat is writing angles.
I might implement `mouse_event`.

[https://github.com/kristofhracza/tim_apple?tab=readme-ov-file#is-this-cheat-read-only](https://github.com/kristofhracza/tim_apple?tab=readme-ov-file#is-this-cheat-read-only)
